name: CI
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches: [master]
    tags:
      - '*'

jobs:
  docs:
   runs-on: ubuntu-latest
   if: github.event.pull_request.draft == false

   steps:
     - name: Checkout
       uses: actions/checkout@v2

     - name: Validate docs
       run: npx elm make --docs=/tmp/docs.json

  example1:
   runs-on: ubuntu-latest
   if: github.event.pull_request.draft == false

   steps:
     - name: Checkout
       uses: actions/checkout@v2

     - name: Validate code
       run: npx elm make examples/Example1.elm --output /dev/null

  example2:
   runs-on: ubuntu-latest
   if: github.event.pull_request.draft == false

   steps:
     - name: Checkout
       uses: actions/checkout@v2

     - name: Validate code
       run: npx elm make examples/Example2.elm --output /dev/null

  example3:
   runs-on: ubuntu-latest
   if: github.event.pull_request.draft == false

   steps:
     - name: Checkout
       uses: actions/checkout@v2

     - name: Validate code
       run: npx elm make examples/Example3.elm --output /dev/null

  example4:
   runs-on: ubuntu-latest
   if: github.event.pull_request.draft == false

   steps:
     - name: Checkout
       uses: actions/checkout@v2

     - name: Validate code
       run: npx elm make examples/Example4.elm --output /dev/null

  example5:
   runs-on: ubuntu-latest
   if: github.event.pull_request.draft == false

   steps:
     - name: Checkout
       uses: actions/checkout@v2

     - name: Validate code
       run: npx elm make examples/Example5.elm --output /dev/null
